"""auto-vote

Revision ID: 088e1a1c0c3f
Revises: e4a0b9fa8e2e
Create Date: 2022-10-19 22:49:45.104730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088e1a1c0c3f'
down_revision = 'e4a0b9fa8e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
